/*
# Test the Server API
*/
@host http://localhost:8080
GET http://localhost:8080/api/produce/67e40f0ec7e47153376b140c.json

HTTP/1.1 200  - OK
x-powered-by: Express
access-control-allow-origin: *
content-type: application/json; charset=utf-8
content-length: 4
etag: W/"4-K+iMpCQsduglOsYkdIUQZQMtaDM"
date: Wed, 26 Mar 2025 15:23:22 GMT
connection: close